#! /bin/sh

xsetroot -cursor_name left_ptr
sxhkd &
clipit &
volumeicon &
nm-applet &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap           0          

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^4'
bspc rule -a Chromium desktop='^2'
bspc rule -a discord desktop='^3'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

feh --bg-center --bg-fill ~/Pictures/background/bg.*
compton --config ~/.config/compton/compton.conf -b
panel &
termite &
